### ISSUE TITLE
May you write more tips about how to run your code?

### ISSUE THREAD

**Issue by lovelyqian** [LeiJiangJNU/DAMDNet#2]
Hi, I just read your paper and I appreciate your work very much especially for providing the code.

however, I only find your evaluating script, and can not find your training script used to train models, so I am wondering if you could write more tips about how to run your code when you are free? such as where to collect datasets and how to process them.

thank you again.

**Comment by LeiJiangJNU** [comment]
Hi，I will update later. Now, you can find some code in https://github.com/cleardusk/3DDFA.

**Comment by lovelyqian** [comment]
> Hi，I will update later. Now, you can find some code in https://github.com/cleardusk/3DDFA.

Thank you very much.
