### ISSUE TITLE
请问怎么将3D人脸贴到2D图像上？

### ISSUE THREAD

**Issue by Light-SH** [LeiJiangJNU/DAMDNet#6]
请问怎么将3D人脸贴到2D图像上，像3D Face Alignment Results中的第(d)行那样？

**Comment by LeiJiangJNU** [comment]
你好。这个使用论文中的公式2，然后经过z-buffer渲染即可。相关代码可以在这里[http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/HPEN/Code/3DMMFitting.zip](url)找到。

**Comment by Light-SH** [comment]
非常感谢你的回复，还有一个问题想请教一下，论文中提到模型的输出只有人脸的形状和表情参数，那在3D Face Alignment Results中的第(d)行的人脸纹理信息是怎么得到的呢

**Comment by LeiJiangJNU** [comment]
你好。纹理信息是从原图中提取的。所以存在遮挡区域纹理不完整的问题。

**Comment by flynnamy** [comment]
@Moon-W 请问你解决了如何将3D人脸贴到2D图像上吗？有没有相应代码？thx
